routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Controller;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\InputServiceController;
use App\Http\Controllers\RekapitulasiController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Example Routes
// Dari Template =======================================================
// Route::view('/', 'landing');
// Route::match(['get', 'post'], '/home', function () {
//     return view('layouts.mitra-main');
// });
// Route::view('/pages/slick', 'pages.slick');
// Route::view('/pages/datatables', 'pages.datatables');
// Route::view('/pages/blank', 'pages.blank');
// Dari Template =======================================================

Route::namespace('App\Http\Controllers')->group(function () {

    //Login
    Route::get('/login', [LoginController::class, 'index'])->name('login')->middleware('guest');
    Route::post('/authenticate', [LoginController::class, 'authenticate'])->name('authenticate');
    Route::get('/logout', [LoginController::class, 'logout']);

    Route::middleware(['auth'])->group(function () {
        Route::get('/', [HomeController::class, 'index']);
        Route::get('/home', [HomeController::class, 'index'])->name('home');

        // Admin
        Route::get('/dashboard', function () {
            return view('pages.dashboard');
        });

        Route::get('/example', function () {
            return view('pages.dashboard');
        });

        Route::get('/rekapitulasi', function () {
            return view('pages.rekapitulasi');
        });

        // Route datamaster
        Route::resource('/datamaster-kategori', KategoriController::class);
        
        Route::resource('/datamaster-user', UserController::class);

        Route::resource('/rekapitulasi', RekapitulasiController::class);

        // Data Service
        Route::resource('/input-service', InputServiceController::class);     
        Route::get('/input-service/{id}/detail', [InputServiceController::class, 'detail'])->name('input-service.detail');   
        Route::put('/input-service/{id}/fix', [InputServiceController::class, 'fix'])->name('input-service.fix');
        Route::put('/input-service/{id}/batal', [InputServiceController::class, 'batal'])->name('input-service.batal');
        Route::put('/input-service/{id}/proses', [InputServiceController::class, 'proses'])->name('input-service.proses');
        Route::put('/input-service/{id}/selesai', [InputServiceController::class, 'selesai'])->name('input-service.selesai');
    });
});

app/Models/Kategori.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Kategori extends Model
{
    use HasFactory;

    protected $table = 'kategori'; //camelcase
    protected $guarded = ['idKategori'];
    protected $primaryKey = 'idKategori';

    protected $fillable = [
        'kategori'
    ];

    public $timestamps = false;

    public function barang()
    {
        return $this->hasMany(Barang::class, 'idKategori');
    }
}

app/Http/Controllers/KategoriController.php
<?php

namespace App\Http\Controllers;

use App\Models\Kategori;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class KategoriController extends Controller
{

    public function index()
    {
        $data = Kategori::all();
        return view('pages.datamaster.kategori.index', [
            'data' => $data
        ]);
    }

    //Create Page
    public function create()
    {
        return view('pages.datamaster.kategori.create',);
    }

    // Insert to database
    public function store(Request $request)
    {
        $category = Kategori::create([
            'kategori' => ($request->input('category'))
        ]);

        return redirect()->route('datamaster-kategori.index');
    }

    // Edit Data
    public function edit(string $id)
    {

        $category = Kategori::find($id);

        return view('pages.datamaster.kategori.edit', [
            'kategori' => $category
        ]);
    }

    public function update(Request $request, $id)
    {
        $category = Kategori::find($id);
        $category->update([
            //? model -------- name html
            'kategori' => $request->input('category')
        ]);

        return redirect()->route('datamaster-kategori.index');
    }


    // Delete data
    public function destroy(string $id)
    {
        $category = Kategori::find($id);
        $category->delete();
        return redirect()
            ->route('datamaster-kategori.index');
    }
}

resources/views/pages/datamaster/kategori/create.blade.php
@extends('layouts.mitra-main')

@section('content')
    <!-- Page Content -->
    <div class="content">
        <div class="block block-rounded">
            <div class="block-header block-header-default">
                <h3 class="block-title">CREATE NEW CATEGORY</h3>
                <nav class="flex-shrink-0 mt-3 mt-sm-0 ms-sm-3 ml-auto" aria-label="breadcrumb">
                    <ol class="breadcrumb breadcrumb-alt">
                        <li class="breadcrumb-item">
                            <a class="link-fx" href="javascript:void(0)">Data Master</a>
                        </li>
                        <li class="breadcrumb-item" aria-current="page">
                            <a class="link-fx" href="javascript:void(0)">Kategori</a>
                        </li>
                        <li class="breadcrumb-item" aria-current="page">
                            Create
                        </li>
                    </ol>
                </nav>
            </div>
            <div class="block-content block-content-full">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-sm-10 col-md-8">
                            {{-- ! Form input kategori --}}
                            <form action="{{ route('datamaster-kategori.store') }}" method="post" id="createCategory">
                                @csrf
                                {{-- ! Naming = category --}}
                                <div class="mb-4">
                                    <label class="form-label" for="category">Category</label><small class="text-danger"> *</small>
                                    <input type="text" class="form-control" id="category" name="category" placeholder="Input Category">
                                </div>
                                <div class="d-flex justify-content-between align-items-center">
                                    <a href="{{ route('datamaster-kategori.index') }}" class="btn btn-secondary">Kembali</a>
                                    <button type="submit" class="btn btn-success"><i class="ik save ik-save"></i>Submit</button>
                                </div>
                            </form>
                            {{-- ! End Form input kategori --}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- END Page Content -->
@endsection

@section('js')
    <script>
        $(document).ready(function() {
            $("#role").select2({
                minimumResultsForSearch: Infinity
            });
        });
    </script>
@endsection

resources/views/pages/datamaster/kategori/edit.blade.php
@extends('layouts.mitra-main')

@section('content')
    <!-- Page Content -->
    <div class="content">
        <div class="block block-rounded">
            <div class="block-header block-header-default">
                <h3 class="block-title">EDIT CATEGORy</h3>
                <nav class="flex-shrink-0 mt-3 mt-sm-0 ms-sm-3 ml-auto" aria-label="breadcrumb">
                    <ol class="breadcrumb breadcrumb-alt">
                        <li class="breadcrumb-item">
                            <a class="link-fx" href="javascript:void(0)">Data Master</a>
                        </li>
                        <li class="breadcrumb-item" aria-current="page">
                            <a class="link-fx" href="javascript:void(0)">Kategori</a>
                        </li>
                        <li class="breadcrumb-item" aria-current="page">
                            Edit
                        </li>
                    </ol>
                </nav>
            </div>
            <div class="block-content block-content-full">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-sm-10 col-md-8">

                            <form action="{{ route('datamaster-kategori.update', $kategori->idKategori) }}" method="POST" id="updateCategory">
                                @method('PUT')
                                @csrf

                                {{-- ! Naming = category --}}
                                <div class="mb-4">
                                    <label class="form-label" for="category">Category</label><small class="text-danger"> *</small>
                                    <input type="text" class="form-control" id="category" name="category" value="{{ $kategori->kategori }}">
                                </div>

                                <div class="d-flex justify-content-between align-items-center">
                                    <a href="{{ route('datamaster-kategori.index') }}" class="btn btn-secondary">Kembali</a>
                                    <button type="submit" class="btn btn-success"><i class="ik save ik-save"></i>Submit</button>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- END Page Content -->
@endsection

@section('js')
    <script>
        $(document).ready(function() {
            $("#role").select2({
                minimumResultsForSearch: Infinity
            });

        });
    </script>
@endsection

resources/views/pages/datamaster/kategori/index.blade.php
@extends('layouts.mitra-main')

@section('title', 'Master Kategori')

@section('content')
    <!-- Hero -->
    <div class="bg-body-light">
        <div class="content content-full">
            <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
                <div class="flex-grow-1">
                    <h1 class="h3 fw-bold mb-2">MANAGE KATEGORI</h1>
                    <nav class="flex-shrink-0 mt-3 mt-sm-0 ms-sm-2" aria-label="breadcrumb">
                        <ol class="breadcrumb breadcrumb-alt">
                            <li class="breadcrumb-item">
                                <a class="link-fx" href="#">Data Master</a>
                            </li>
                            <li class="breadcrumb-item" aria-current="page">
                                Kategori
                            </li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- END Hero -->

    <!-- Page Content -->
    <div class="content">

        <!-- Dynamic Table Full -->
        <div class="block block-rounded">
            <div class="block-header block-header-default">
                <h3 class="block-title">
                    Table Kategori
                </h3>

                <a href="{{ route('datamaster-kategori.create') }}" class="btn btn-bg btn-success my-2">
                    <i class="fa fa-plus me-1"></i>
                    <span style="font-size: 12px; line-height: 12px;" class="block-title">Add Kategori</span>
                </a>

            </div>
            <div class="block-content block-content-full">
                <!-- DataTables init on table by adding .js-dataTable-full class, functionality is initialized in js/pages/tables_datatables.js -->
                <table class="table table-bordered table-striped table-vcenter js-dataTable-full fs-sm">
                    <thead>
                        <tr>
                            <th class="text-center" style="width: 80px;">No</th>
                            <th class="text-center">Nama Kategori</th>
                            <th class="text-center" style="width: 15%;">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($data as $data)
                            <tr>
                                <td class="text-center">{{ $loop->iteration }}</td>
                                <td class="fw-semibold text-center">{{ $data->kategori }}</td>
                                <td class="text-center">

                                    {{-- Button edit and delete --}}
                                    <form action="{{ route('datamaster-kategori.destroy', $data->idKategori) }}" method="POST">
                                        @csrf
                                        @method('delete')

                                        <a href="{{ route('datamaster-kategori.edit', $data->idKategori) }}" class="btn btn-sm btn-primary">
                                            <i class="nav-main-link-icon bi bi-pencil-square"></i>
                                        </a>

                                        <button type="submit" class="btn btn-sm btn-danger"
                                            onclick="return confirm('Apakah Anda yakin menghapus data ini?');">
                                            <i class="nav-main-link-icon bi bi-trash"></i>
                                        </button>

                                    </form>

                                </td>
                            </tr>
                        @endforeach

                    </tbody>
                </table>
            </div>
        </div>
        <!-- END Dynamic Table Full -->

    </div>
    <!-- END Page Content -->
@endsection