routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Controller;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\InputServiceController;
use App\Http\Controllers\RekapitulasiController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Example Routes
// Dari Template =======================================================
// Route::view('/', 'landing');
// Route::match(['get', 'post'], '/home', function () {
//     return view('layouts.mitra-main');
// });
// Route::view('/pages/slick', 'pages.slick');
// Route::view('/pages/datatables', 'pages.datatables');
// Route::view('/pages/blank', 'pages.blank');
// Dari Template =======================================================

Route::namespace('App\Http\Controllers')->group(function () {

    //Login
    Route::get('/login', [LoginController::class, 'index'])->name('login')->middleware('guest');
    Route::post('/authenticate', [LoginController::class, 'authenticate'])->name('authenticate');
    Route::get('/logout', [LoginController::class, 'logout']);

    Route::middleware(['auth'])->group(function () {
        Route::get('/', [HomeController::class, 'index']);
        Route::get('/home', [HomeController::class, 'index'])->name('home');

        // Admin
        Route::get('/dashboard', function () {
            return view('pages.dashboard');
        });

        Route::get('/example', function () {
            return view('pages.dashboard');
        });

        Route::get('/rekapitulasi', function () {
            return view('pages.rekapitulasi');
        });

        // Route datamaster
        Route::resource('/datamaster-kategori', KategoriController::class);
        
        Route::resource('/datamaster-user', UserController::class);

        Route::resource('/rekapitulasi', RekapitulasiController::class);

        // Data Service
        Route::resource('/input-service', InputServiceController::class);     
        Route::get('/input-service/{id}/detail', [InputServiceController::class, 'detail'])->name('input-service.detail');   
        Route::put('/input-service/{id}/fix', [InputServiceController::class, 'fix'])->name('input-service.fix');
        Route::put('/input-service/{id}/batal', [InputServiceController::class, 'batal'])->name('input-service.batal');
        Route::put('/input-service/{id}/proses', [InputServiceController::class, 'proses'])->name('input-service.proses');
        Route::put('/input-service/{id}/selesai', [InputServiceController::class, 'selesai'])->name('input-service.selesai');
    });
});

resources/views/pages/service/create.blade.php
@extends('layouts.mitra-main')

@section('title', 'Input Service')

@section('content')

    <!-- Page Content -->
    <div class="content">
        {{-- Input Data Customer --}}
        <div class="block block-rounded">
            <div class="block-header block-header-default">
                <h3 class="block-title">INPUT BARANG</h3>
                <nav class="flex-shrink-0 mt-3 mt-sm-0 ms-sm-3 ml-auto" aria-label="breadcrumb">
                    <ol class="breadcrumb breadcrumb-alt">
                        <li class="breadcrumb-item">
                            <a class="link-fx" href="{{ route('input-service.index') }}">Data Service</a>
                        </li>
                        <li class="breadcrumb-item" aria-current="page">
                            Input Barang
                        </li>
                    </ol>
                </nav>
                
            </div>
            <div class="block-content block-content-full">
                {{-- Form input data --}}
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-sm-10 col-md-8">
                <form action="{{ route('input-service.store') }}" method="POST" id="insertCustomer">
                    @csrf
                    <div class="row">
                        <div class="col">
                            <label class="form-label" for="namaCustomer">Nama</label><small class="text-danger"> *</small>
                            <input type="text" class="form-control" id="namaCustomer" name="namaCustomer" placeholder="Nama Customer">
                        </div>
                        <div class="col">
                            <label class="form-label" for="noHp">No HP</label><small class="text-danger"> *</small>
                            <input type="text" class="form-control" id="noHP" name="noHP" placeholder="081234567891">
                        </div>
                    </div>

                    <div class="mt-4">
                        <label class="form-label" for="alamat">Alamat</label><small class="text-danger"> *</small>
                        <textarea class="form-control" id="alamat" name="alamat" placeholder="Masukan alamat customer"></textarea>
                    </div>

                    <div class="row mt-4">
                        <div class="col">
                            <label class="form-label" for="namaBarang">Nama Barang</label><small class="text-danger"> *</small>
                            <input type="text" class="form-control" id="namaBarang" name="namaBarang" placeholder="Nama Customer">
                        </div>
                        <div class="col">
                            <label class="form-label" for="kategoriBarang">Kategori Barang</label><small class="text-danger"> *</small>
                            <select class="form-select" name="kategori" id="kategori">
                                <option>Pilih Kategori</option>
                                @foreach ($kategori as $kategori)
                                    <option value="{{ $kategori->idKategori }}">{{ $kategori->kategori }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="mt-4">
                        <label class="form-label" for="kelengkapan">Kelengkapan Barang</label><small class="text-danger"> *</small>
                        <textarea class="form-control" id="kelengkapan" name="kelengkapan" placeholder="Masukan kelengkapan barang"></textarea>
                    </div>

                    <div class="mt-4">
                        <label class="form-label" for="tanggalMasuk">Tanggal Masuk</label><small class="text-danger"> *</small>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Tanggal</span>
                            </div>
                            <input type="date" class="form-control" id="tanggalMasuk" name="tanggalMasuk" placeholder="DD-MM-YYYY">
                        </div>
                    </div>

                    <div class="d-flex justify-content-end mt-4">
                        <button type="submit" class="btn btn-primary">
                            <span class="me-1">Simpan</span>
                            <i class="nav-main-link-icon bi bi-sd-card"></i>
                        </button>
                    </div>

                </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {{-- End Input Data Customer --}}

    </div>
    <!-- END Page Content -->










@endsection

resources/views/pages/service/index.blade.php
@extends('layouts.mitra-main')

@section('title', 'Data Service')
@section('content')
  <!-- Hero -->
  <div class="bg-body-light">
    <div class="content content-full">
      <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center py-2">
        <div class="flex-grow-1">
          <h1 class="h3 fw-bold mb-2">
           DATA SERVICE
          </h1>
          <nav class="flex-shrink-0 mt-3 mt-sm-0 ms-sm-3" aria-label="breadcrumb">
            <ol class="breadcrumb breadcrumb-alt">
              <li class="breadcrumb-item">
                <a class="link-fx" href="javascript:void(0)">Data Service</a>
              </li>
              <li class="breadcrumb-item" aria-current="page">
                Barang
              </li>
            </ol>
          </nav>
        </div>
        <a href="{{ route('input-service.create') }}" class="btn btn-bg btn-success">
            <i class="bi bi-folder-plus"></i> Input Barang
        </a>

      </div>
    </div>
  </div>
  <!-- END Hero -->

  <!-- Page Content -->
  <div class="content">

    <!-- Dynamic Table Full -->
    <div class="block block-rounded">
      <div class="block-header block-header-default">
        <h3 class="block-title">
          Table Barang
        </h3>
      </div>
      <div class="block-content block-content-full">
        <!-- DataTables init on table by adding .js-dataTable-full class, functionality is initialized in js/pages/tables_datatables.js -->
        <table class="table table-bordered table-striped table-vcenter js-dataTable-full fs-sm">
          <thead>
            <tr>
              <th class="text-center" style="width: 50px;">#</th>
              <th class="text-center" >Barang</th>
              <th class="text-center" style="width: 15%;">Kategori</th>
              <th class="text-center" style="width: 15%;">Customer</th>
              <th class="text-center" style="width: 15%;">Tanggal Masuk</th>
              <th class="text-center" style="width: 15%;">Status</th>
              <th class="text-center" style="width: 20%;">Aksi</th>
            </tr>
          </thead>
          <tbody>
            @foreach ($data as $data)
            <tr>
                <td class="text-center">{{ $loop->iteration }}</td>
                <td class="fw-semibold text-center">{{ $data->namaBarang }}</td>
                <td class="fw-semibold text-center">{{ $data->kategori->kategori }}</td>
                <td class="fw-semibold text-center">{{ $data->customer->namaCustomer }}</td>
                <td class="fw-semibold text-center">{{ $data->tanggalMasuk }}</td>
                <td class="fw-semibold text-center">
                  @if ($data->status == 'pengecekan')
                    <span style="width: 150px;" class="fs-xs fw-semibold d-inline-block py-1 px-3 rounded-pill bg-warning-light text-warning">Dalam Pengecekan</span>
                  @elseif ($data->status == 'perbaikan')
                    <span style="width: 150px;" class="fs-xs fw-semibold d-inline-block py-1 px-3 rounded-pill bg-warning-light text-warning">Dalam Perbaikan</span>
                  @elseif ($data->status == 'selesaicek')
                    <span style="width: 150px;" class="fs-xs fw-semibold d-inline-block py-1 px-3 rounded-pill bg-info-light text-info">Selesai dicek</span>
                  @elseif ($data->status == 'selesai')
                    <span style="width: 150px;" class="fs-xs fw-semibold d-inline-block py-1 px-3 rounded-pill bg-success-light text-success">SERVICE SELESAI</span>
                  @elseif ($data->status == 'batal')
                    <span style="width: 150px;" class="fs-xs fw-semibold d-inline-block py-1 px-3 rounded-pill bg-danger-light text-danger">DIBATALKAN</span>
                  @endif
                </td>

                <td class="text-center">
                  @if ($data->status == 'pengecekan')
                    <button type="button" style="width: 180px;" class="btn btn-sm btn-primary" id="fixButton" data-toggle="modal" data-target="#fixModal" data-id="{{ $data->idBarang }}">
                      <i class="nav-main-link-icon bi bi-check-circle"></i> Selesai Cek 
                    </button>
                  @elseif($data->status == 'selesaicek')
                    <button type="button" style="width: 90px;" class="btn btn-sm btn-primary" id="prosesButton" data-toggle="modal" data-target="#prosesModal" data-id="{{ $data->idBarang }}">
                      <i class="nav-main-link-icon bi bi-tools"></i> Proses
                    </button>
                    <button type="button" style="width: 90px;" class="btn btn-sm btn-danger" id="batalButton" data-toggle="modal" data-target="#batalModal" data-id="{{ $data->idBarang }}">
                      <i class="nav-main-link-icon bi bi-x-circle"></i> Batal
                    </button>
                  @elseif($data->status == 'batal')
                    {{-- <button type="button" style="width: 180px;" class="btn btn-sm btn-secondary" id="detailbatalButton" data-toggle="modal" data-target="#detailbatalModal" data-id="{{ $data->idBarang }}">
                      <i class="nav-main-link-icon bi bi-info-circle"></i> Detail
                    </button> --}}
                    @elseif($data->status == 'selesai')
                    <button type="button" style="width: 180px;" class="btn btn-sm btn-light" id="detailButton" data-toggle="modal" data-target="#detailModal" data-id="{{ $data->idBarang }}">
                      <i class="nav-main-link-icon bi bi-clipboard-data"></i> Detail Service
                    </button>
                  @elseif($data->status == 'perbaikan')
                    <button type="button" style="width: 180px;" class="btn btn-sm btn-success" id="selesaiButton" data-toggle="modal" data-target="#selesaiModal" data-id="{{ $data->idBarang }}">
                      <i class="nav-main-link-icon bi bi-check-circle"></i> Selesai
                    </button>
                    {{-- <button type="button" style="width: 90px;" class="btn btn-sm btn-secondary" id="detailButton" data-toggle="modal" data-target="#detailModal" data-id="{{ $data->idBarang }}">
                      <i class="nav-main-link-icon bi bi-info-circle"></i> Info
                    </button> --}}
                  @endif
                </td>
            </tr>
        @endforeach
          </tbody>
        </table>
      </div>
    </div>
    <!-- END Dynamic Table Full -->
  </div>
  <!-- END Page Content -->

 @include('pages.service.modals.fix')
 @include('pages.service.modals.batal')
 @include('pages.service.modals.proses')
 @include('pages.service.modals.selesai')
 @include('pages.service.modals.detail')

   

@endsection