routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Controller;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\InputServiceController;
use App\Http\Controllers\RekapitulasiController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Example Routes
// Dari Template =======================================================
// Route::view('/', 'landing');
// Route::match(['get', 'post'], '/home', function () {
//     return view('layouts.mitra-main');
// });
// Route::view('/pages/slick', 'pages.slick');
// Route::view('/pages/datatables', 'pages.datatables');
// Route::view('/pages/blank', 'pages.blank');
// Dari Template =======================================================

Route::namespace('App\Http\Controllers')->group(function () {

    //Login
    Route::get('/login', [LoginController::class, 'index'])->name('login')->middleware('guest');
    Route::post('/authenticate', [LoginController::class, 'authenticate'])->name('authenticate');
    Route::get('/logout', [LoginController::class, 'logout']);

    Route::middleware(['auth'])->group(function () {
        Route::get('/', [HomeController::class, 'index']);
        Route::get('/home', [HomeController::class, 'index'])->name('home');

        // Admin
        Route::get('/dashboard', function () {
            return view('pages.dashboard');
        });

        Route::get('/example', function () {
            return view('pages.dashboard');
        });

        Route::get('/rekapitulasi', function () {
            return view('pages.rekapitulasi');
        });

        // Route datamaster
        Route::resource('/datamaster-kategori', KategoriController::class);
        
        Route::resource('/datamaster-user', UserController::class);

        Route::resource('/rekapitulasi', RekapitulasiController::class);

        // Data Service
        Route::resource('/input-service', InputServiceController::class);     
        Route::get('/input-service/{id}/detail', [InputServiceController::class, 'detail'])->name('input-service.detail');   
        Route::put('/input-service/{id}/fix', [InputServiceController::class, 'fix'])->name('input-service.fix');
        Route::put('/input-service/{id}/batal', [InputServiceController::class, 'batal'])->name('input-service.batal');
        Route::put('/input-service/{id}/proses', [InputServiceController::class, 'proses'])->name('input-service.proses');
        Route::put('/input-service/{id}/selesai', [InputServiceController::class, 'selesai'])->name('input-service.selesai');
    });
});

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    protected $table = 'user';
    protected $primaryKey = 'idUser';
    public $timestamps = false;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'username',
        'password',
        'role',
        'status'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        // 'password' => 'hashed',
    ];

    public function barang()
    {
        return $this->hasMany(Barang::class, 'idUser');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{

    public function index()
    {
        $data = User::all();
        return view('pages.datamaster.user.index', [
            'data' => $data
        ]);
    }

    public function create()
    {
        return view('pages.datamaster.user.create',);
    }

    public function store(Request $request)
    {
        $user = User::create([
            'username' => ($request->input('username')),
            'password' => Hash::make($request->input('password')),
            'role' => ($request->input('role')),
        ]);

        return redirect()->route('datamaster-user.index');
    }

    public function edit(string $id)
    {

        $user = User::find($id);

        return view('pages.datamaster.user.edit', [
            'user' => $user
        ]);
    }

    public function update(Request $request, $id)
    {
        // Create an array with the data to update
        $user = User::find($id);
        $data = [
            'username' => $request->input('username'),
            'role' => $request->input('role'),
        ];

        // Check if a new password was provided
        if ($request->filled('password')) {
            // Hash the new password and add it to the data
            $data['password'] = Hash::make($request->input('password'));
        }

        // Update the user with the combined data

        $user->update($data);

        return redirect()->route('datamaster-user.index');
    }



    public function destroy(string $id)
    {

        $user = User::find($id);
        $user->delete();

        return redirect()
            ->route('datamaster-user.index');
    }
}

resources/views/pages/datamaster/user/create.blade.php
@extends('layouts.mitra-main')

@section('content')
    <!-- Page Content -->
    <div class="content">
        <div class="block block-rounded">
            <div class="block-header block-header-default">
                <h3 class="block-title">CREATE NEW USER</h3>
                <nav class="flex-shrink-0 mt-3 mt-sm-0 ms-sm-3 ml-auto" aria-label="breadcrumb">
                    <ol class="breadcrumb breadcrumb-alt">
                        <li class="breadcrumb-item">
                            <a class="link-fx" href="javascript:void(0)">Data Master</a>
                        </li>
                        <li class="breadcrumb-item" aria-current="page">
                            <a class="link-fx" href="javascript:void(0)">User</a>
                        </li>
                        <li class="breadcrumb-item" aria-current="page">
                            Create
                        </li>
                    </ol>
                </nav>
            </div>
            <div class="block-content block-content-full">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-sm-10 col-md-8">
                            <form action="{{ route('datamaster-user.store') }}" method="POST" id="createUser">
                                @csrf
                                <div class="mb-4">
                                    <label class="form-label" for="username">Username</label><small class="text-danger"> *</small>
                                    <input type="text" class="form-control" id="username" name="username" placeholder="Your Username..">
                                </div>
                                <div class="mb-4">
                                    <label class="form-label" for="password">Password</label><small class="text-danger"> *</small>
                                    <input type="password" class="form-control" id="password" name="password" placeholder="Your Password..">
                                </div>
                                <div class="mb-4">
                                    <label class="form-label" for="role">Role</label><small class="text-danger"> *</small>
                                    <select class="form-control" name="role" id="role">
                                        <option selected disabled value="">-- Pilih Role --</option>

                                        <option value="admin">Admin</option>
                                        <option value="superadmin">Superadmin</option>

                                    </select>
                                </div>
                                <div class="d-flex justify-content-between align-items-center">
                                    <a href="{{ route('datamaster-user.index') }}" class="btn btn-secondary">Kembali</a>
                                    <button type="submit" class="btn btn-success"><i class="ik save ik-save"></i>Submit</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- END Page Content -->
@endsection

@section('js')
    <script>
        $(document).ready(function() {
            $("#role").select2({
                minimumResultsForSearch: Infinity
            });
        });
    </script>
@endsection

resources/views/pages/datamaster/user/edit.blade.php
@extends('layouts.mitra-main')

@section('content')
    <!-- Page Content -->
    <div class="content">
        <div class="block block-rounded">
            <div class="block-header block-header-default">
                <h3 class="block-title">EDIT USER</h3>
                <nav class="flex-shrink-0 mt-3 mt-sm-0 ms-sm-3 ml-auto" aria-label="breadcrumb">
                    <ol class="breadcrumb breadcrumb-alt">
                        <li class="breadcrumb-item">
                            <a class="link-fx" href="javascript:void(0)">Data Master</a>
                        </li>
                        <li class="breadcrumb-item" aria-current="page">
                            <a class="link-fx" href="javascript:void(0)">User</a>
                        </li>
                        <li class="breadcrumb-item" aria-current="page">
                            Edit
                        </li>
                    </ol>
                </nav>
            </div>
            <div class="block-content block-content-full">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-sm-10 col-md-8">
                            <form action="{{ route('datamaster-user.update', $user->idUser) }}" method="POST" id="createUser">
                                @method('PUT')
                                @csrf
                                <div class="mb-4">
                                    <label class="form-label" for="username">Username</label><small class="text-danger"> *</small>
                                    <input type="text" class="form-control" id="username" name="username" value="{{ $user->username }}"
                                        placeholder="Your Username..">
                                </div>
                                <div class="mb-4">
                                    <label class="form-label" for="password">Password</label><small class="text-danger"> *</small>
                                    <input type="password" class="form-control" id="password" name="password" placeholder="Masukkan password baru..">
                                </div>
                                <div class="mb-4">
                                    <label class="form-label" for="role">Role</label><small class="text-danger"> *</small>
                                    <select name="role" id="role" class="form-control">
                                        <option value="admin" {{ $user->role === 'admin' ? 'selected' : '' }}>Admin</option>
                                        <option value="superadmin" {{ $user->role === 'superadmin' ? 'selected' : '' }}>Superadmin</option>
                                        <!-- Add more options for different roles if needed -->
                                    </select>
                                </div>
                                <div class="d-flex justify-content-between align-items-center">
                                    <a href="{{ route('datamaster-user.index') }}" class="btn btn-secondary">Kembali</a>
                                    <button type="submit" class="btn btn-success"><i class="ik save ik-save"></i>Submit</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- END Page Content -->
@endsection

@section('js')
    <script>
        $(document).ready(function() {
            $("#role").select2({
                minimumResultsForSearch: Infinity
            });

        });
    </script>
@endsection

resources/views/pages/datamaster/user/index.blade.php
@extends('layouts.mitra-main')

@section('title', 'Master User')
@section('content')

    <!-- Hero -->
    <div class="bg-body-light">
        <div class="content content-full">
            <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
                <div class="flex-grow-1">
                    <h1 class="h3 fw-bold mb-2">MANAGE USER</h1>
                    <nav class="flex-shrink-0 mt-3 mt-sm-0 ms-sm-2" aria-label="breadcrumb">
                        <ol class="breadcrumb breadcrumb-alt">
                            <li class="breadcrumb-item">
                                <a class="link-fx" href="#">Data Master</a>
                            </li>
                            <li class="breadcrumb-item" aria-current="page">
                                User
                            </li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- END Hero -->

    <!-- Page Content -->
    <div class="content">
        <!-- Dynamic Table Full -->
        <div class="block block-rounded">
            <div class="block-header block-header-default">
                <h3 class="block-title">
                    Table User
                </h3>
                <a href="{{ route('datamaster-user.create') }}" class="btn btn-bg btn-success my-2">
                    <i class="fa fa-plus me-1"></i>
                    <span class="block-title" style="font-size: 12px; line-height: 12px;">Add User</span>
                </a>
            </div>
            <div class="block-content block-content-full">
                <!-- DataTables init on table by adding .js-dataTable-full class, functionality is initialized in js/pages/tables_datatables.js -->
                <table class="table table-bordered table-striped table-vcenter js-dataTable-full fs-sm">
                    <thead>
                        <tr>
                            <th class="text-center" style="width: 80px;">No</th>
                            <th>Username</th>
                            <th class="d-none d-sm-table-cell" style="width: 25%;">Role</th>
                            <th class="d-none d-sm-table-cell" style="width: 25%;">Status</th>
                            <th style="width: 15%;">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($data as $data)
                            <tr>
                                <td class="text-center">{{ $loop->iteration }}</td>
                                <td class="fw-semibold">{{ $data->username }}</td>
                                <td class="fw-semibold">{{ ucwords($data->role) }}</td>
                                <td class="fw-semibold">{{ ucwords($data->status) }}</td>
                                <td class="text-center">
                                    <form action="{{ route('datamaster-user.destroy', $data->idUser) }}" method="POST">
                                        @csrf
                                        @method('delete')

                                        <a href="{{ route('datamaster-user.edit', $data->idUser) }}" class="btn btn-sm btn-primary">
                                            <i class="nav-main-link-icon bi bi-pencil-square"></i>
                                        </a>

                                        <button type="submit" class="btn btn-sm btn-danger"
                                            onclick="return confirm('Apakah Anda yakin menghapus data ini?');">
                                            <i class="nav-main-link-icon bi bi-trash"></i>
                                        </button>

                                    </form>
                                </td>
                            </tr>
                        @endforeach

                    </tbody>
                </table>
            </div>
        </div>
        <!-- END Dynamic Table Full -->

    </div>
    <!-- END Page Content -->
@endsection